baseURL = "/"
languageCode = "pt-br"
title = "Beatriz🖤 Latina Cutie"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  version = "1.0.0"
  description = "25 anos | Aventureira e cheia de atitude.
Sempre pronta para uma nova jornada, com uma pitada de ousadia e sensualidade
🔥 Picante e destemida quando a vibe está certa"